### ISSUE TITLE
[Bug] <Metadata as object>

### ISSUE THREAD

**Issue by JanKulbinski** [pinecone-io/spark-pinecone#29]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hi! I have problem with loading data to pinecone with spark connector. I’ve tried to follow [this](https://docs.pinecone.io/integrations/databricks) page from documentation. But in the article metadata is defined as plain string:

```
schema = StructType([  
    StructField("id",StringType(),True),  
    StructField("values",ArrayType(FloatType()),True),  
    StructField("namespace",StringType(),True),  
    StructField("metadata", StringType(), True),  
    StructField("sparse_values", StructType([  
        StructField("indices", ArrayType(IntegerType(), False), False),  
        StructField("values", ArrayType(FloatType(), False), False)  
    ]), True)  
])  
```
In my case I want to define metadata as object with 2 fields, as:

```
StructField(
    "metadata",
    StructType(
        [
            StructField("A", ArrayType(StringType(), False), False),
            StructField("B", StringType(), False),
        ]
    ),
    True,
),
```
But after such a definition I got error when trying load data into Pinecone:
- Cannot write 'metadata': struct<A:array<string>,B:string> is incompatible with string

### Expected Behavior

I' like to be able to import object as metadata, since I could do that in plain python.

### Steps To Reproduce
Try to import data with metadata, as:

```
StructField(
    "metadata",
    StructType(
        [
            StructField("A", ArrayType(StringType(), False), False),
            StructField("B", StringType(), False),
        ]
    ),
    True,
),
```

### Relevant log output

```shell
- Cannot write 'metadata': struct<A:array<string>,B:string> is incompatible with string
```

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by lugonthier** [comment]
Hi,

If you look at the [source code](https://github.com/pinecone-io/spark-pinecone/blob/db7d6c2e88c2919db6919c0d99d73d3b098da5e9/src/main/scala/io/pinecone/spark/pinecone/package.scala#L36), it's expecting the _**the JSON string representing the vector's metadata**_.

To get it, you can use the sql function `to_json`. It will convert your metadata (`StructType`) to a JSON string.

```python
from pyspark.sql.functions import to_json

df.select(
        col("id"),
        col("namespace"),
        col("values"),
        to_json(col("metadata")),
        col("sparse_values")
)
```

**Comment by rohanshah18** [comment]
Thanks @lugonthier for responding! @JanKulbinski closing this issue but if you have any further issues, feel free to open this or a new one.
