### ISSUE TITLE
[Bug] Inaccessible jar on s3 and library not working on Databricks

### ISSUE THREAD

**Issue by mdagost** [pinecone-io/spark-pinecone#6]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The Pinecone [docs page](https://docs.pinecone.io/docs/databricks) for Databricks lists the location `s3://pinecone-jars/spark-pinecone-uberjar.jar`.  However, on Databricks (or even via the AWS CLI), access to that bucket is denied.

The README for this repo says "We also release a shaded uber jar to maven that's compatible with Databricks."  When installed from Maven, that version of the library--spark-pinecone_2.12 version 0.1.1--doesn't work on Databricks either.

First, the code from the docs has the embedding vector in the schema named `vector`, but the library requires it to be called `values`.  But even with that change, the code:

```
(
    to_upsert
    .write
    .option("pinecone.apiKey", "XXX")
    .option("pinecone.environment", "XXX")
    .option("pinecone.projectName", "XXX")
    .option("pinecone.indexName", "XXX")
    .format("io.pinecone.spark.pinecone.Pinecone")
    .mode("append")
    .save()
)
```

results in

```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 4 times, most recent failure: Lost task 0.3 in stage 6.0 (TID 31) (10.52.160.240 executor 0): java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.NettyChannelBuilder
```

with 10.4 LTS of the Databricks runtime--Apache Spark 3.2.1, Scala 2.12.

Is there a supported way to connect to Pinecone from Databricks that works?

### Expected Behavior

The location of the library should be accessible.  The library in the README that says it's supported should work.

### Steps To Reproduce

`aws s3 ls s3://pinecone-jars/spark-pinecone-uberjar.jar`

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by rajat08** [comment]
Hey @mdagost  
We'll fix the issues with the s3 location. Looking at the error you are seeing, this is likely coming from not using the shaded version of the library (because there are conflicts with our gRPC and with DBR). The s3 location does have that, but since it's not accessible, you can get the shaded jar from Maven as well. You can use this in your pom to use the shaded version than the regular version as it says in the Readme: 
```
<dependency>
  <groupId>io.pinecone</groupId>
  <artifactId>spark-pinecone_2.12</artifactId>
  <version>0.1.1</version>
  <classifier>assembly</classifier>
</dependency>
```
(Note the extra classifier tag to differentiate it from the regular version) 
If this does not work too please let me know

**Comment by mdagost** [comment]
Thanks for the response.  I'll keep an eye out for the fixed s3 location.  I don't think Databricks works with a pom--the only relevant option is to install from Maven Central, and I don't see any way to get that assembly tag:

![Screen Shot 2023-06-09 at 10 04 51 AM](https://github.com/pinecone-io/spark-pinecone/assets/1334817/9f10d350-b7b6-4556-a7e5-351b81c4cd6f)

**Comment by mdagost** [comment]
Though I guess I can try downloading it directly and uploading it to s3 myself:

https://repo1.maven.org/maven2/io/pinecone/spark-pinecone_2.13/0.1.1/spark-pinecone_2.13-0.1.1-assembly.jar

**Comment by rajat08** [comment]
> Though I guess I can try downloading it directly and uploading it to s3 myself:
> 
> https://repo1.maven.org/maven2/io/pinecone/spark-pinecone_2.13/0.1.1/spark-pinecone_2.13-0.1.1-assembly.jar

You can do that; I also update the jar on s3. You should be able to download it now

**Comment by mdagost** [comment]
Still not working on Databricks:

```
Library installation attempted on the driver node of cluster 0607-212709-auvzzs8x and failed. Please refer to the following error message to fix the library or contact Databricks support. Error Code: DRIVER_LIBRARY_INSTALLATION_FAILURE. Error Message: java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: s3a://pinecone-jars/spark-pinecone-uberjar.jar: getFileStatus on s3a://pinecone-jars/spark-pinecone-uberjar.jar: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD https://pinecone-jars.s3.us-east-1.amazonaws.com spark-pinecone-uberjar.jar
```

**Comment by mdagost** [comment]
Locally the command `aws s3 ls s3://pinecone-jars/spark-pinecone-uberjar.jar` fails with AccessDenied, but `aws s3 cp s3://pinecone-jars/spark-pinecone-uberjar.jar` works.  So I think you need to add a list/head permission.

**Comment by mdagost** [comment]
Also, I downloaded that and manually uploaded it to Databricks and it still doesn't work.  What is the supported Spark and Scala version for the jar at s3://pinecone-jars/spark-pinecone-uberjar.jar?

```
Py4JJavaError: An error occurred while calling o634.save.
: java.lang.NoSuchMethodError: scala.runtime.ScalaRunTime$.wrapRefArray([Ljava/lang/Object;)Lscala/collection/immutable/ArraySeq;
```

**Comment by rajat08** [comment]
> Also, I downloaded that and manually uploaded it to Databricks and it still doesn't work. What is the supported Spark and Scala version for the jar at s3://pinecone-jars/spark-pinecone-uberjar.jar?
> 
> ```
> Py4JJavaError: An error occurred while calling o634.save.
> : java.lang.NoSuchMethodError: scala.runtime.ScalaRunTime$.wrapRefArray([Ljava/lang/Object;)Lscala/collection/immutable/ArraySeq;
> ```

Looks like you are using the 2.13 version which Databricks does not support, you can try the 2.12 build [from here](https://repo1.maven.org/maven2/io/pinecone/spark-pinecone_2.12/0.1.1/spark-pinecone_2.12-0.1.1-assembly.jar). 
I have also added list object permissions on the object so it should be accessible. I realize the documentation around things are poor, I will make sure to add some

**Comment by mdagost** [comment]
What I meant is that I had downloaded the jar `3://pinecone-jars/spark-pinecone-uberjar.jar` and re-uploaded it and got that error.  So if that's 2.13, then that means the the wrong jar is at that location for Databricks, no?

Incidentally, I just tried installing directly via Databricks again and get the same error:

```
Library installation attempted on the driver node of cluster 0607-212709-auvzzs8x and failed. Please refer to the following error message to fix the library or contact Databricks support. Error Code: DRIVER_LIBRARY_INSTALLATION_FAILURE. Error Message: java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: s3a://pinecone-jars/spark-pinecone-uberjar.jar: getFileStatus on s3a://pinecone-jars/spark-pinecone-uberjar.jar: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD https://pinecone-jars.s3.us-east-1.amazonaws.com spark-pinecone-uberjar.jar 
```

I'm going to try downloading and re-uploading the 2.12 assembly jar from Maven.

**Comment by mdagost** [comment]
The `spark-pinecone_2.12-0.1.1-assembly.jar` jar from maven does work with databricks runtime 13.0, which is Apache Spark 3.4.0, Scala 2.12.

**Comment by rajat08** [comment]
Glad to hear you are temporarily unblocked. I am going to follow up with the following on our end : 
- Ensure jar on s3 has proper access & is the scala 2.12 version
- Test across different DBR versions to ensure compatibility 
- Improve documentation to reduce confusion. 
cc : @gdj0nes

**Comment by olgaakrekhovetska** [comment]
Hey @rajat08!.
Both, `[spark-pinecone_2.12-0.1.1-assembly.jar](https://repo1.maven.org/maven2/io/pinecone/spark-pinecone_2.12/0.1.1/spark-pinecone_2.12-0.1.1-assembly.jar)` and `[spark-pinecone-uberjar.jar](s3://pinecone-jars/spark-pinecone-uberjar.jar)` work, but in order to use them one will need to manually download them and then add to Databricks cluster. This might work for some testing purpose.
For prod ready solution it would be great to have any of these libraries available in Maven, when can we expect to have it?

**Comment by olgaakrekhovetska** [comment]
By they way, I tried to shade libraries as it was recommended in README:

```
ThisBuild /assembly /assemblyShadeRules := Seq(
  ShadeRule.rename("com.google.protobuf.**" -> "shade.com.google.protobuf.@1").inAll,
  ShadeRule.rename("com.google.common.**" -> "shade.com.google.common.@1").inAll
)
```

It results in exception:
```
cannot find a NameResolver for <index_name>-<project_id>.svc.us-east4-gcp.pinecone.io
Caused by: IllegalArgumentException: cannot find a NameResolver for i<index_name>-<project_id>.svc.us-east4-gcp.pinecone.io
```

**Comment by rajat08** [comment]
@olgaakrekhovetska 
Thanks for bringing it up; we plan to do a release soon and we will push it to Maven. Did the assembly classifier in Maven not work for you?

Regarding the exception, is this something you see during builds or while running code? I don't think this is what should be used by the NameResolver :```i<index_name>-<project_id>.svc.us-east4-gcp.pinecone.io```, it should be using your index name and project for the lookup

**Comment by olgaakrekhovetska** [comment]
This is an error from runtime. 

> I don't think this is what should be used by the NameResolver :i<index_name>-<project_id>.svc.us-east4-gcp.pinecone.io, it should be using your index name and project for the lookup


You are correct, I substituted real index name and project id by placeholders on purpose in order to share error message here.

**Comment by rajat08** [comment]
> This is an error from runtime.
> 
> > I don't think this is what should be used by the NameResolver :i<index_name>-<project_id>.svc.us-east4-gcp.pinecone.io, it should be using your index name and project for the lookup
> 
> You are correct, I substituted real index name and project id by placeholders on purpose in order to share error message here.

I see, this might be coming from Netty, I haven't seen this before. Can you paste the stack trace?

**Comment by olgaakrekhovetska** [comment]
`java.lang.IllegalArgumentException: cannot find a NameResolver for <index_name>-<project_id>.svc.us-east4-gcp.pinecone.i
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:776)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:785)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:665)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at io.pinecone.PineconeConnection.buildChannel(PineconeConnection.java:99)
	at io.pinecone.PineconeConnection.<init>(PineconeConnection.java:44)
	at io.pinecone.PineconeClient.connect(PineconeClient.java:37)
	at io.pinecone.spark.pinecone.PineconeDataWriter.<init>(PineconeDataWriter.scala:27)
	at io.pinecone.spark.pinecone.PineconeDataWriterFactory.createWriter(PineconeDataWriterFactory.scala:10)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run(WriteToDataSourceV2Exec.scala:493)
	at org.apache.spark.sql.execution.datasources.v2.WritingSparkTask.run$(WriteToDataSourceV2Exec.scala:482)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:557)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:445)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:82)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:82)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:196)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:181)
	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:146)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:41)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:99)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:104)
	at scala.util.Using$.resource(Using.scala:269)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:103)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:146)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$8(Executor.scala:897)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1681)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:900)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:795)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)`

**Comment by olgaakrekhovetska** [comment]
@rajat08

Are [spark-pinecone_2.12-0.1.1-assembly.jar ](https://repo1.maven.org/maven2/io/pinecone/spark-pinecone_2.12/0.1.1/spark-pinecone_2.12-0.1.1-assembly.jar)and [spark-pinecone-uberjar.jar](s3://pinecone-jars/spark-pinecone-uberjar.jar) sbt-managed projects?

In case yes, could you provide shade rules that are defined for these two?

**Comment by rajat08** [comment]
> @rajat08
> 
> Are [spark-pinecone_2.12-0.1.1-assembly.jar ](https://repo1.maven.org/maven2/io/pinecone/spark-pinecone_2.12/0.1.1/spark-pinecone_2.12-0.1.1-assembly.jar)and spark-pinecone-uberjar.jar sbt-managed projects?
> 
> In case yes, could you provide shade rules that are defined for these two?

Yes they are sbt projects, you can see the shading rules [here](https://github.com/pinecone-io/spark-pinecone/blob/main/build.sbt).

**Comment by rohanshah18** [comment]
@mdagost I have published the new version of spark-pinecone connector v0.1.4 and tested it on databricks (DBR 14.1: Spark 3.5.0 and Scala 2.12) with spark-pinecone assembly jar successfully. You can find the assembly jar for Spark 3.5.0  and Scala 2.12 here:
s3://pinecone-jars/spark-pinecone-uberjar.jar

Please let me know if you are still facing the issue.

**Comment by rohanshah18** [comment]
Closing this since I haven't heard back and hoping the new release has resolved your issue.

**Comment by mdagost** [comment]
@rohanshah18 For posterity: on a fresh cluster with Databricks runtime 14.1, I see that this works.  But when I specify a custom iam role for the cluster (which we need to access our other resources) I get the access denied message.  I had to alter our custom iam role to specifically add:

```
statement {
    sid = "S3PineconeJarBucket"
    actions = [
      "s3:GetBucketLocation",
      "s3:ListBucket",
      "s3:GetObject",
    ]
    resources = [
      "arn:aws:s3:::pinecone-jars",
      "arn:aws:s3:::pinecone-jars/*",
    ]
  }

```

It's odd, because this is a public bucket, but 🤷
