### ISSUE TITLE
Question on write mode

### ISSUE THREAD

**Issue by ctaylor-catalyst** [pinecone-io/spark-pinecone#7]
I am not sure I fully understand the documentation:
> The write itself is not atomic, but pinecone is an idempotent key value store which should keep our desired state. 

I see the examples of writing a spark dataframe all use the append mode. Am I to understand write to pinecone is essentially an upsert operation, "appending" new vectorized info to an existing index? In other words, as long as we make sure the initial data does not share IDs, we can use the "append" mode to update the vector store?

**Comment by rohanshah18** [comment]
@ctaylor-catalyst Yes, you have the correct understanding that writing to spark dataframe is an upsert operation (underlying java sdk upsert operation).
