### ISSUE TITLE
Can 'sparse_values' be passed in the current implementation?

### ISSUE THREAD

**Issue by edwinpgm** [pinecone-io/spark-pinecone#9]
I'm currently working on integrating PySpark with Pinecone for embedding storage. In my implementation, I need to pass sparse_values along with other fields, but the current setup doesn't seem to allow for this.

The issue arises when attempting to pass sparse_values. Despite trying different approaches, I haven't been successful in including it in the data sent to Pinecone.

I'd greatly appreciate any guidance or suggestions on how to handle sparse_values in this context. Thank you!

**Comment by rohanshah18** [comment]
@edwinpgm Thanks for creating this issue, I'll be adding the ability to pass the sparse vectors. The supported versions for the spark connector will be 3.4.1 for spark and 2.12+ for scala.

**Comment by edwinpgm** [comment]
> @edwinpgm Thanks for creating this issue, I'll be adding the ability to pass the sparse vectors. The supported versions for the spark connector will be 3.4.1 for spark and 2.12+ for scala.

Thanks @rohanshah18

**Comment by rohanshah18** [comment]
@edwinpgm I have released `v0.2.1` for spark-pinecone connector. Please note that this will require Spark `v3.5.0` and if you're intending to use databricks platform, please import the assembly jar from S3: `s3://pinecone-jars/0.2.1/spark-pinecone-uberjar.jar`.

Release notes for your reference: https://github.com/pinecone-io/spark-pinecone/releases/tag/v0.2.1

I have also provided examples on how to upsert the sparse vectors in the release notes. Please let me know if this resolves your issue.

**Comment by edwinpgm** [comment]
> @edwinpgm I have released `v0.2.1` for spark-pinecone connector. Please note that this will require Spark `v3.5.0` and if you're intending to use databricks platform, please import the assembly jar from S3: `s3://pinecone-jars/0.2.1/spark-pinecone-uberjar.jar`.
> 
> Release notes for your reference: https://github.com/pinecone-io/spark-pinecone/releases/tag/v0.2.1
> 
> I have also provided examples on how to upsert the sparse vectors in the release notes. Please let me know if this resolves your issue.

Thanks a lot, @rohanshah18! I'll give it a try this week and provide feedback if any adjustments are needed.

**Comment by rohanshah18** [comment]
@edwinpgm I'll close this issue for now since I have also tested it in databricks platform but if you have any problems, feel free to open another issue.
